### ISSUE TITLE
T4_Diagrama de clases

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/practica-de-diagrama-de-clases-systems#1]
[DiagramaDeClases_ProyectoHorizon.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-clases-systems/files/7824970/DiagramaDeClases_ProyectoHorizon.pdf)

**Comment by ArturoAngonJose** [comment]
Calificacion:30/30

**Comment by josealfredo79** [comment]
faltan las conclusiones

**Comment by josealfredo79** [comment]
ademas la calificacion asignada no es la correcta

**Comment by josealfredo79** [comment]
asignar por favor la calificacion correctaq

**Comment by AndreLuna6** [comment]
[DiagramaDeClases_ProyectoHorizon.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-clases-systems/files/7831937/DiagramaDeClases_ProyectoHorizon.pdf)

**Comment by Ferch0419** [comment]
Calificado: 30/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado
